### ISSUE TITLE
Including OSMNet in other packages' requirements - now fixed

### ISSUE THREAD

**Issue by smmaurer** [UDST/osmnet#15]
### Problem

People sometimes get errors using `setuptools` to install packages that list OSMNet as a requirement. 

For example, OSMNet is a requirement in Pandana's `setup.py` file. If you install Pandana on OS X or Linux using `python setup.py develop`, and OSMNet is not yet installed, you get the error below.

### Solution

I poked around, and it seems like the problem is that the initial 0.1.0 release of OSMNet on pypi.org included files that no longer conform to the standard naming spec. This causes an error when `setuptools` tries to find an appropriate version to install. 

There are several newer releases, none of which break the API in any way, so I went ahead and removed 0.1.0 from pypi. This immediately fixed the problem on my machine.

Let me know if you see any more issues related to this.

### Original error message

```
Searching for osmnet>=0.1.2
Reading https://pypi.org/simple/osmnet/
Traceback (most recent call last):
  File "setup.py", line 133, in <module>
    'License :: OSI Approved :: GNU Affero General Public License v3'
  File "/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 156, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/anaconda3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/anaconda3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    not self.always_copy, self.local_index
  File "/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 658, in fetch_distribution
    self.find_packages(requirement)
  File "/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 491, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 831, in scan_url
    self.process_url(url, True)
  File "/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 373, in process_url
    self.process_url(link)
  File "/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 335, in process_url
    dists = list(distros_for_url(url))
  File "/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 99, in distros_for_url
    for dist in distros_for_location(url, base, metadata):
  File "/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 118, in distros_for_location
    wheel = Wheel(basename)
  File "/anaconda3/lib/python3.6/site-packages/setuptools/wheel.py", line 64, in __init__
    raise ValueError('invalid wheel name: %r' % filename)
ValueError: invalid wheel name: 'osmnet-0.1.0-py2.py3-any.whl'
```

**Comment by sablanchard** [comment]
via @smmaurer this was fixed by updating the settings on pypi.org
